spring:
  application:
    name: deliveats

  profiles:
    active: dev

  config:
    import: optional:classpath:/application-oauth.yml

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.deliveats: DEBUG
